name: build

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-coverage
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest --cov --cov-report xml
      - name: Creating the coverage folder
        run: |
          mkdir -p coverage
      - name: Create the coverage badge
        uses: tj-actions/coverage-badge-py@v1.8
        with:
          output: coverage/coverage.svg
      - name: Publish the coverage report
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: coverage-badge
          folder: coverage
